name: Package Python Executable (Windows)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache pip wheel cache
        uses: actions/cache@v3
        with:
          path: C:\Users\RunnerAdmin\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # - name: Cache project venv
      #   id: cache-venv
      #   uses: actions/cache@v3
      #   with:
      #     path: .venv
      #     key: ${{ runner.os }}-venv-${{ hashFiles('**/uv.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-venv-

      - name: Cache global pip packages
        id: cache-tooling
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}\Lib\site-packages
          key: ${{ runner.os }}-global-pip-uv-pyinstaller-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-global-pip-uv-pyinstaller-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install tooling
        if: steps.cache-tooling.outputs.cache-hit != 'true'
        run: pip install uv pyinstaller

      - name: Create virtual environment
        run: uv venv

      - name: Sync dependencies
        run: uv sync --all-groups

      - name: Build executable
        shell: pwsh
        run: uv run pyinstaller --noconfirm knowlang/api/main.spec

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: knowlang-executable
          path: dist/main/main.exe
