name: Python Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      
    - name: Install dependencies
      run: |
        poetry install --with dev  # This installs both main and dev dependencies
        
    - name: Run tests with pytest
      run: |
        poetry run pytest

